# Generated by Django 3.2.20 on 2023-08-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus',
            new_name='google_plus_link',
        ),
    ]
